name: flutter_samples
description: Flutter apps samples

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0-nullsafety.0
  dotted_border: ^2.0.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/common/images/
    - assets/delivery_app/icons/
    - assets/delivery_app/images/
    - assets/facebook_ui/icons/
    - assets/facebook_ui/images/
    - assets/facebook_ui/images/collections/
    - assets/facebook_ui/images/people/
    - assets/facebook_ui/images/profile/
    - assets/facebook_ui/images/stories/

  # example:
  fonts:
    - family: Lexend
      fonts: 
        - asset: assets/common/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/common/fonts/Lexend/Lexend-Light.ttf
        - asset: assets/common/fonts/Lexend/Lexend-Medium.ttf
        - asset: assets/common/fonts/Lexend/Lexend-Regular.ttf
        - asset: assets/common/fonts/Lexend/Lexend-SemiBold.ttf

    - family: Mulish
      fonts: 
        - asset: assets/common/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/common/fonts/Mulish/Mulish-Light.ttf
        - asset: assets/common/fonts/Mulish/Mulish-Medium.ttf
        - asset: assets/common/fonts/Mulish/Mulish-Regular.ttf
        - asset: assets/common/fonts/Mulish/Mulish-SemiBold.ttf